lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - assets/nf-core-germline_logo_light.png
    - docs/images/nf-core-germline_logo_light.png
    - docs/images/nf-core-germline_logo_dark.png
    - CITATIONS.md
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  files_unchanged:
    - LICENSE
  actions_ci: false
repository_type: pipeline
template:
  author: nvnieuwk
  description: A nextflow pipeline for calling and annotating small germline variants from short DNA reads for WES and WGS data
  name: germline
  prefix: nf-cmgg
