<<<<<<< HEAD
channels:
  - conda-forge
  - bioconda
=======
name: tabix_tabix

channels:
  - conda-forge
  - bioconda
  - defaults
>>>>>>> 3726a041a4fa98d73748421c2a5e8a5b3cd6e7c1

dependencies:
  - bioconda::htslib=1.20
  - bioconda::tabix=1.11
