contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nf-cmgg-germline channel"
    url: https://nfcore.slack.com/channels/nf-cmgg-germline
    about: Discussion about the CenterForMedicalGeneticsGhent/nf-cmgg-germline pipeline
