<<<<<<< HEAD
channels:
  - conda-forge
  - bioconda
=======
name: untar
channels:
  - conda-forge
  - bioconda
  - defaults
>>>>>>> 3726a041a4fa98d73748421c2a5e8a5b3cd6e7c1
dependencies:
  - conda-forge::grep=3.11
  - conda-forge::sed=4.8
  - conda-forge::tar=1.34
